[2024-04-29T13:45:14.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T13:45:14.785+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:11.986126+00:00 [queued]>
[2024-04-29T13:45:14.796+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:11.986126+00:00 [queued]>
[2024-04-29T13:45:14.796+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T13:45:14.816+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): export_csv> on 2024-04-29 13:45:11.986126+00:00
[2024-04-29T13:45:14.825+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'export_csv_to_azure_blob', 'export_csv', 'manual__2024-04-29T13:45:11.986126+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/export_csv.py', '--cfg-path', '/tmp/tmp24fuw_op']
[2024-04-29T13:45:14.829+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask export_csv
[2024-04-29T13:45:14.832+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T13:45:14.833+0000] {standard_task_runner.py:63} INFO - Started process 216 to run task
[2024-04-29T13:45:14.896+0000] {task_command.py:426} INFO - Running <TaskInstance: export_csv_to_azure_blob.export_csv manual__2024-04-29T13:45:11.986126+00:00 [running]> on host 270d16ab0cac
[2024-04-29T13:45:15.016+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='export_csv_to_azure_blob' AIRFLOW_CTX_TASK_ID='export_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T13:45:11.986126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T13:45:11.986126+00:00'
[2024-04-29T13:45:15.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T13:45:15.034+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T13:45:15.035+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/export_csv.py", line 16, in export_csv_to_azure_blob
    blob_client = BlobServiceClient.from_connection_string(AZURE_CONNECTION_STRING, AZURE_CONTAINER_NAME)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", line 190, in from_connection_string
    account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/base_client.py", line 368, in parse_connection_str
    conn_str = conn_str.rstrip(";")
               ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rstrip'
[2024-04-29T13:45:15.048+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=export_csv_to_azure_blob, task_id=export_csv, execution_date=20240429T134511, start_date=20240429T134514, end_date=20240429T134515
[2024-04-29T13:45:15.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task export_csv ('NoneType' object has no attribute 'rstrip'; 216)
[2024-04-29T13:45:15.089+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T13:45:15.126+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T13:45:15.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
